workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m2

    environment:
      node: 20

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Prepare Capacitor
        script: |
          npx cap add ios || true
          npx cap sync ios

      - name: Build iOS
        script: |
          cd ios/App
          pod install
          xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -sdk iphoneos \
          CODE_SIGNING_ALLOWED=NO

    artifacts:
      - ios/App/build/**/*.app
      - ios/App/build/**/*.ipa
