workflows:
  ios-workflow:
    name: iOS Build
    environment:
      node: 20
      xcode: latest

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web
        script: npm run build

      - name: Sync capacitor
        script: npx cap sync ios

      - name: Build iOS
        script: |
          cd ios/App
          pod install
          xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -sdk iphoneos \
          -configuration Release \
          archive -archivePath $CM_BUILD_DIR/App.xcarchive
